name: Release to PyPi

on: workflow_dispatch
jobs:
  release_to_pypi:
    name: Release distribution to pypi.org
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: Build wheel
        if: startsWith(github.ref, 'refs/tags')
        run: |
          set -e
          
          version=$(git describe --tags --abbrev=7)
          
          pip install virtualenv
          python -m virtualenv hadoopwrapper
          
          . hadoopwrapper/bin/activate
          pip install --upgrade twine build
          
          echo "__version__ = '$version'" > ./src/spark_utils/_version.py
          
          python -m build --sdist --wheel
      - name: Publish distribution ðŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
